name: Zip Static Website

on:
  push:
    branches:
      - main  # Change if your branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create ZIP File
        run: zip -r static-website.zip .

      - name: Upload ZIP File
        uses: actions/upload-artifact@v3
        with:
          name: static-website-zip
          path: static-website.zip
